language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip setuptools wheel

install:
  - travis_wait pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - make travis

after_success: coveralls

notifications:
  email: silpa-discuss@nongnu.org
  irc:
    channels:
    on_success: #silpa
    on_failure: #silpa
    use_notice: true
